### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by damdam-s** [akretion/roulier#18]
``` bash
(env) USER@WORKSTATION:~$ pip install roulier==0.0.0
Collecting roulier==0.0.0
  Downloading roulier-0.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-4KXwP2/roulier/setup.py", line 6, in <module>
        version = open('VERSION').read().strip()
    IOError: [Errno 2] No such file or directory: 'VERSION'
```
I'm investigating but not so used to build pip installable package :(

**Comment by hparfr** [comment]
It seams related to pypi install. 

As a quick workaround, you can still do : 
`pip install https://github.com/akretion/roulier/archive/0.0.1.tar.gz`

**Comment by hparfr** [comment]
FYI :  VERSION file was not included in build.
You can now `pip install roulier==0.0.1`

**Comment by damdam-s** [comment]
@hparfr thanks a lot
