### ISSUE TITLE
Traceback when use laposte api 

### ISSUE THREAD

**Issue by saxomanu** [akretion/roulier#96]
When i want to use this api, i have a traceback 
>>> -> from roulier import roulier     
>>> -> laposte = roulier.get('laposte')
>>> -> laposte.api()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/roulier/roulier/carriers/laposte/laposte.py", line 19, in api
    return self.encoder.api()
  File "/root/roulier/roulier/carriers/laposte/laposte_encoder.py", line 52, in api
    return api.api_values()
  File "/root/roulier/roulier/api.py", line 158, in api_values
    return self.normalize({})
  File "/root/roulier/roulier/api.py", line 180, in normalize
    return self._validator().normalized(data, self.api_schema())
  File "/root/roulier/roulier/api.py", line 133, in api_schema
    schemas = self._schemas()
  File "/root/roulier/roulier/carriers/laposte/laposte_api.py", line 150, in _schemas
    schemas = super(LaposteApi, self)._schemas()
  File "/root/roulier/roulier/api.py", line 116, in _schemas
    'parcels': self._parcels(),
  File "/root/roulier/roulier/api.py", line 89, in _parcels
    'default': [v.normalized({}, self._parcel())]
  File "/usr/local/lib/python3.5/dist-packages/cerberus/validator.py", line 593, in normalized
    self.__init_processing(document, schema)
  File "/usr/local/lib/python3.5/dist-packages/cerberus/validator.py", line 548, in __init_processing
    self.schema = DefinitionSchema(self, schema)
  File "/usr/local/lib/python3.5/dist-packages/cerberus/schema.py", line 69, in __init__
    self.validate(schema)
  File "/usr/local/lib/python3.5/dist-packages/cerberus/schema.py", line 197, in validate
    self._validate(schema)
  File "/usr/local/lib/python3.5/dist-packages/cerberus/schema.py", line 218, in _validate
    if not self.schema_validator(schema, normalize=False):
  File "/usr/local/lib/python3.5/dist-packages/cerberus/validator.py", line 879, in validate
    self.__validate_unknown_fields(field)
  File "/usr/local/lib/python3.5/dist-packages/cerberus/validator.py", line 912, in __validate_unknown_fields
    if not validator({field: value}, normalize=False):
  File "/usr/local/lib/python3.5/dist-packages/cerberus/validator.py", line 877, in validate
    self.__validate_definitions(definitions, field)
  File "/usr/local/lib/python3.5/dist-packages/cerberus/validator.py", line 940, in __validate_definitions
    result = validate_rule(rule)
  File "/usr/local/lib/python3.5/dist-packages/cerberus/validator.py", line 922, in validate_rule
    return validator(definitions.get(rule, None), field, value)
  File "/usr/local/lib/python3.5/dist-packages/cerberus/validator.py", line 1236, in _validate_schema
    self.__validate_schema_mapping(field, schema, value)
  File "/usr/local/lib/python3.5/dist-packages/cerberus/validator.py", line 1247, in __validate_schema_mapping
    if not validator(value, update=self.update, normalize=False):
  File "/usr/local/lib/python3.5/dist-packages/cerberus/validator.py", line 877, in validate
    self.__validate_definitions(definitions, field)
  File "/usr/local/lib/python3.5/dist-packages/cerberus/validator.py", line 940, in __validate_definitions
    result = validate_rule(rule)
  File "/usr/local/lib/python3.5/dist-packages/cerberus/validator.py", line 921, in validate_rule
    validator = self.__get_rule_handler('validate', rule)
  File "/usr/local/lib/python3.5/dist-packages/cerberus/validator.py", line 338, in __get_rule_handler
    "domain.".format(rule, domain))
RuntimeError: There's no handler for 'description' in the 'validate' domain.

I tried with python2.7 and python3.5 with the same result.
What i'm doing wrong ?

**Comment by saxomanu** [comment]
I solved the problem by downgrade version of cerberus to 1.1 instead of 1.2
